spring:
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: h2
      schema-locations: classpath:/db/schema-h2.sql
      data-locations: classpath:/db/common-data-h2.sql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:db;NON_KEYWORDS=KEY,DAY
