spring:
  messages:
    encoding: UTF-8
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      add-mappings: false
  sql:
    init:
      schema-locations: classpath:schema.sql,classpath:views.sql
      data-locations: classpath:data.sql
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true


